services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 main:app
    envVars:
      - key: BOT_TOKEN
        value: 7611666697:AAH6aLkRF7jYBmvEWAHWnePLz6OEb_49VOI
